name: opendrift_p2
channels:
  - conda-forge
dependencies:
  - python=2.7
  - matplotlib
  - numpy>=1.15.4
  - scipy>=1.2.0
  - netcdf4>=1.4.3
  - future
  - ffmpeg
  - pillow
  - pyproj>=2.2
  - configobj
  - libgdal>=2.3.3
  - gdal>=2.3.3
  - ipython
  - pip
  - pytest
  - pytest-cov
  - pytest-benchmark
  - cartopy
  - pip:
    - https://github.com/matplotlib/basemap/archive/a551c2361314670dc7d95143190d3d48ba750d20.zip

