name: opendrift_p2_oil
channels:
  - conda-forge
  - NOAA-ORR-ERD
dependencies:
  - python=2.7
  - matplotlib
  - numpy>=1.15.4
  - scipy>=1.2.0
  - netcdf4>=1.4.3
  - future
  - ffmpeg
  - pillow
  - pyproj>=2.2
  - configobj
  - libgdal>=2.3.3
  - gdal>=2.3.3
  - gitpython
  - pip
  - pytest
  - pytest-cov
  - pytest-benchmark
  - SQLAlchemy>=1.3
  - zope.sqlalchemy>=1.1
  - awesome-slugify
  - backports.functools_lru_cache>=1.5
  - unit_conversion>=2.5
  - cartopy
  - rasterio
  - pip:
    - https://github.com/matplotlib/basemap/archive/a551c2361314670dc7d95143190d3d48ba750d20.zip
    - git+https://github.com/OpenDrift/OilLibrary.git@python2
    - git+https://github.com/OpenDrift/opendrift-landmask-data.git
