pycallable:     schism.wrapper.SCHISMHC

# Main ======================================================================
imp:            ppb2d
mode:           hindcast
#stack:          &STACK gfs  #[gfs, ec, None]

id:             schism_ppb2d
version:        v1.0
description:    &DESC  SCHISM/WWM Port Phillip Bay 2D - Australia
title:          &TITLE SCHISM/WWM Port Phillip Bay 2D - Australia
active:         True

rootdir:        /scratch/hindcast/schism/gfs_ppb2d
staticdir:      /static/hindcast/schism/ppb2d/ # static files (e.g. model grids) directory
sitesfile:      /config/hindcast/models/schism/sites.ppb2d.xml
updir:          /data/schism/gfs_ppb2d/
hotdir:         /hot/hindcast/schism/gfs_ppb2d/
logdir:         /logs/hindcast/schism/gfs_ppb2d/

run_length:     0  # days
dtout:          3  # recording interval [h]
dtout3d:        3  # recording interval [h]
spinup:         0 # days to run before actual nowcast time
hclen:          0 # days of forecast to run before forecast
cycle_lock:     False

model_version:  v5.6.0
modelexec:      pschism_5.6.0_HYDRO_VL_WWM
mpiexec:        /usr/lib64/mpich/bin/mpiexec


# ============================================================================
model_config:
    Name: ppb2d implementation
    id:   &NEST ppb2d
    Data:
        meteo:
            id:      meteo
            name:    ppb2d meteo data
            format:  nc
            udshost: http://uds-ops.service.consul:9191/uds
            dset:    &METEO ['wrf_gfs_seaus-bass', 'wrf_gfs_seaus-seaus', 'gfs_sfc_sub']
            vars:    [ugrd10m, vgrd10m, mslp]
            Grid:    {x: 143.0, x2: 146.5, y: -39.8, y2: -37.3, dx: 0.075, dy: 0.075}
        ocean:
            name:    ppb2d ocean data
            id:      ocean
            format:  nc
            udshost: http://uds-ops.service.consul:9191/uds
            dset:    &OCEAN [roms_gfs_saus2d-sfc]
            vars:    [umo, vmo, ssh]
            Grid:    {x: 143.0, x2: 146.5, y: -39.8, y2: -37.3, dx: 0.04, dy: 0.04}
        wave:
            name:    ppb2d wave data
            id:      wave
            format:  nc
            udshost: http://uds-ops.service.consul:9191/uds
            dset:    &WAVE [swan_gfs_aus-bass]
            vars:    [hs, tp, dpm, dspr, tm02]
            Grid:    {x: 143.0, x2: 146.5, y: -39.8, y2: -37.3, dx: 0.04, dy: 0.04}

    Nest:
        ppb2d:
            name:         ppb2d implementation 
            
            Physics:  
                momentum: &PHYSICS 2D
                coupling: &COUPLING WWM

            Timestep: 
                dt: 120.
                dt_wwm: 2. # SCHISM calls WWM every this 'N' time steps [WWMdt=dt*dt_wmm] 

            Static: 
                bathy:
                    file: /bathytopo/somewhere.nc
                hgrid: 
                    type:  fort.14
                    #epsg: #3577 # GDA94 - Australian Albers [https://epsg.io/3577]
                    epsg:  4326
                    file:  /static/hindcast/schism/ppb2d/ppb2d_hgrid.gr3
                vgrid:
                    ivcor:  2 # ivcor: 1:LSC2 & 2:S/SZ [vgrid type] 
                    nlev:   2
                    hc:     5
                    thetab: 0
                    thetas: 10
                    file:   /static/hindcast/schism/ppb2d/ppb2d_vgrid.in

            WWM_params:
                igridtype: 3 #SCHISM

            Params:           
                itur:  3
                turb_met:  KL
                turb_stab: KC
                xlsc0: 0.1
                inv_atm_bnd: 0

            Property:
                tvd:       1       # Transport option (0=upwind; 1=TVD/TVD2)
                drag:      0.0028 # [manning, drag (Cd), rough (bottom roughness in meters)] 
                diffmin:   0.0001 # if itur={3,4}
                diffmax:   5.0 # if itur={3,4}
                windrot_geo2proj: 0 # ['rotate': to apply coordsys transformation, 'float': if constant values]

            Meteo: 
                type:      FILE
                source:    meteo

            Ocean:
                type:   FILE
                source: ocean

            Wave: 
                type:      FILE
                source:    wave
                nature:    spec  # nature of wave forcing ['param': parametric, 'spec': spectra]
                bnd:       {type: 2} #type 2: active bnd (Dirichlet).
                spectrum:  {nfreq: 21, ndir: 24, flow: 0.02, fhigh: 0.5}
                # spectrum:  {nfreq: 23, ndir: 36, flow: 0.04, fhigh: 0.6666} SWAN-bass example
                hotstart:  {stepback: 0} # stepback in days
                

            Tide: 
                type:      FILE 
                source:    tsm_tide # OTIS 0.03deg
                #source:   bass_tide # MOS-POM 0.03deg
                nature:    cons # ['ts': timeseries, 'cons': constituients]
                filename:  /static/hindcast/schism/ppb2d/ppb2d_tidecons-tsm-otis.nc   
            
            Bnd:
                type:   FILE
                source: ocean
                btype:  1 # boundary type num.
                elevation:   {type: 5}
                velocity:    {type: 5}
                temperature: {type: 0}
                salinity:    {type: 0}

            Output:
                elev :  1 # elev.
                dahv :  1 # depth-averaged vel.
                wind :  1 # wind speed
                zcor :  1 # z-coordinates
                WWM_1:  1 # hs
                WWM_2:  1 # tm01
                WWM_3:  1 # tm02
                WWM_11: 1 # tp
                WWM_18: 1 # dpm
                WWM_19: 1 # dspr

            WWM_output:
                write: False
                hs : T # significant wave height



# Scheduler configs =========================================================

schedule:
    docker:
        image: metocean/schism:0.9.0
        # host: True
        # environment: 
        #     START_SSH_SERVER: 1
        #     SSH_SERVER_PORT: 2222

        volumes:     
            - '/data/schism:/data/schism'
            - '/hot:/hot'
            - '/flush:/flush'
            - '/scratch:/scratch'
            - '/static:/static'
            - '/ocean/:/ocean/'
    priority:   1
    allocate:        
        cores:  24
        strategy: explicit # balanced (even cores per node), spread (as much possible per node), or explicit (node) - this is default
        min_cores: 1 # minimum number of cores per node
    
    itiles: 2
    jtiles: 14 
    mpi: true 
    routing_key:
        # - '#.sexo.#'
        - '#.xeon.'
        # - '#.xeon.1'
        # - '#.xeon.2'
        # - '#.xeon.3'
        # - '#.xeon.4'
        # - '#.xeon.5'
        # - '#.xeon.6'
        # - '#.iwa.2'
    
    hard_dependency: ['model.schism_ppb2d:-1']
    countdown:        5h
    expires:          30d
    soft_time_limit:  12h
    max_retries:      5
    retry_delay:      5min
    memleak_threshold: 14000
    cycles:
        frequency: DAILY
        interval: 1