# Template for config file
# reproduce run found in example_benchmark_regular
# 
# pycallable:     schism.wrapper.SCHISMHC
# 
# ======================================================================
imp:  test_config_OpenDrift # implementation name
model: OpenOil3D
weathering_model: 'noaa'
extra_model_args: {} # these will be passed as **kwargs in __init__() function
# ======================================================================
# release
nb_parts: 1000
start_time: '01-01-2004 00:00'
end_time:   '08-01-2004 00:00'
position: {lon: 174.1656,lat: -40.3346, radius: 10.,z: 0.0} # z can be 'seafloor' or 'seafloor+2' or 'surface' , or scalar
# end_position: {elon: 174.1656,elat: -40.3346, eradius: 10.,ez: 0.0} #  optional, final lon,lat,z
extra_seed_args: {} # these will be passed as **kwargs in seed_elements() function
# additional seeding arguments as specified in seed_elements() function of each model
# e.g. extra_seed_args: {objectType: 26} # 26 = Life-raft, no ballast
# 
# frame
model_frame:    {llcrnrlon: 168.0199, llcrnrlat: -42.8449 , urcrnrlon: 177.4601 , urcrnrlat: -37.9051}
basemap_resolution: 'h' # resolution can be c (crude, the default), l (low), i (intermediate), h (high), f (full)
# ======================================================================
# readers
# specified using {reader_type: reader_filename, ...} reader_type can be any found in 'from opendrift.readers'  
readers:
    ocean: # specify one or several reader_type and filenames - order matters and will govern priority
        reader_type: [reader_netCDF_MetOcean] #reader_type can be any found in 'from opendrift.readers'  
        filename: ['F:/metocean/R&D_OpenDrift/benchmark_runs/cnz20040101_00z_surf.nc'] # can be many files
        options: {use_log_profile: True, z0: 0.001}
        #vars: [um,vm] #optional to restrict which variables are used
        # will be passed as kwargs to reader's __init__()
        # add option for uds download ? or maybe it will be a new reader_type ? like cmems ?
    meteo:
    wave:

fallback_values: {ocean_vertical_diffusivity: 0.0001} # used to define constant or fall back values
# ======================================================================
# timing and outputs
time_step_sec: 900 #= 900  # 15 minutes
time_step_sec_output: 1800 #= timedelta(minutes=30)
# duration_hours: 24.0 #= int(self.durationhours.get())*3600/time_step
end_time_run: '08-01-2004 00:00' #not used if duration is specified
run_backwards: False
stop_on_error: True
outfile: output_config_test.nc #self.outputdir + '/opendrift_'  # could be defined by default from implemtation name ?
extra_output_args: {} # additional outputs arguments as specified in run()
# ======================================================================
# configuration : base inherited from basemodel + model-specific configs 
# e.g.
# https://github.com/OpenDrift/opendrift/blob/1323f4a47cb16b2ebd818d6c3c302036331e36a7/opendrift/models/basemodel.py#L123
# https://github.com/OpenDrift/opendrift/blob/1323f4a47cb16b2ebd818d6c3c302036331e36a7/opendrift/models/opendrift3D.py#L55
# https://github.com/OpenDrift/opendrift/blob/1323f4a47cb16b2ebd818d6c3c302036331e36a7/opendrift/models/opendrift3D.py#L55
# 
# if nothing specfied, default config is used 
config:
    general:
        coastline_action: 'stranding' # option('none', 'stranding', 'previous', default='stranding')
    seed:
        ocean_only: True #boolean(default=True)
    drift:
        scheme: 'runge-kutta4'
        current_uncertainty: 0.05
        wind_uncertainty: 2.0
        # max_age_seconds: float(min=0, default=None)
        # scheme: option('euler', 'runge-kutta4', 'runge-kutta4', default='euler')
        # stokes_drift: boolean(default=True)
        # current_uncertainty: float(min=0, max=5, default=0)
        # current_uncertainty_uniform: float(min=0, max=5, default=0)
        # wind_uncertainty: float(min=0, max=5, default=0)
        # relative_wind: boolean(default=False)
        # lift_to_seafloor: boolean(default=True)
        # truncate_ocean_model_below_m: float(min=0, max=10000, default=None)
        # deactivate_north_of: float(min=-90, max=90, default=None)
        # deactivate_south_of: float(min=-90, max=90, default=None)
        # deactivate_east_of: float(min=-360, max=360, default=None)
        # deactivate_west_of: float(min=-360, max=360, default=None)
        # use_tabularised_stokes_drift: boolean(default=False)
        # tabularised_stokes_drift_fetch: option(5000, 25000, 50000, default=25000)
    processes:
        turbulentmixing: False
        verticaladvection: False
# post-processing
post_process:
    show_anim:  False
    save_anim:  False
    show_plot:  True
    save_plot:  False
    show_oil_budget: False
    save_oil_budget: False
    # more to come

# ======================================================================
# ======================================================================
# Fall back values
# o.fallback_values['ocean_vertical_diffusivity']: 0.0001
# etc...
# 
# ======================================================================

#
# in opendrift
# o.set_config('general:coastline_action','stranding')
# 
# example of config from basemodel
# [general]
#     use_basemap_landmask: boolean(default=True)
#     basemap_resolution: option('f', 'h', 'i', 'c', default='h')
#     coastline_action: option('none', 'stranding', 'previous', default='stranding')
#     time_step_minutes: integer(min=1, max=1440, default=60)
#     time_step_output_minutes: integer(min=1, max=1440, default=None)
# [seed]
#     ocean_only: boolean(default=True)
# [drift]
#     max_age_seconds: float(min=0, default=None)
#     scheme: option('euler', 'runge-kutta4', 'runge-kutta4', default='euler')
#     stokes_drift: boolean(default=True)
#     current_uncertainty: float(min=0, max=5, default=0)
#     current_uncertainty_uniform: float(min=0, max=5, default=0)
#     wind_uncertainty: float(min=0, max=5, default=0)
#     relative_wind: boolean(default=False)
#     lift_to_seafloor: boolean(default=True)
#     truncate_ocean_model_below_m: float(min=0, max=10000, default=None)
#     deactivate_north_of: float(min=-90, max=90, default=None)
#     deactivate_south_of: float(min=-90, max=90, default=None)
#     deactivate_east_of: float(min=-360, max=360, default=None)
#     deactivate_west_of: float(min=-360, max=360, default=None)
#     use_tabularised_stokes_drift: boolean(default=False)
#     tabularised_stokes_drift_fetch: option(5000, 25000, 50000, default=25000)

# For oceandrift3D: '''
# [processes]
#     turbulentmixing: boolean(default=True)
#     verticaladvection: boolean(default=True)
# [turbulentmixing]
#     timestep: float(min=0.1, max=3600, default=60.)
#     verticalresolution: float(min=0.01, max=10, default: 1.)
#     diffusivitymodel: option('environment', 'stepfunction', 'windspeed_Sundby1983', 'windspeed_Large1994', 'gls_tke', default='environment')
#     TSprofiles: boolean(default=False)
# 
# for leeway
# self._add_config('seed:object_type', descriptions, 'Object type',overwrite=True)# Default jibe probability is 4% per hour
# self._add_config('seed:jibeProbability','float(min=0, max=1, default=0.04)', 'Jibe probability', overwrite=True)

# self._add_config('general:time_step_minutes',
#                  'integer(min=1, max=1440, default=10)',
#                  'Time step in minutes',
#                  overwrite=True)
# self._add_config('general:time_step_output_minutes',
#                  'integer(min=1, max=1440, default=60)',
#                  'Output time step in minutes',overwrite=True)