# Template for config file
# reproduce run found in example_benchmark_regular
# 
#  Example based on example_reader_boundary.py
#  use thredds url as reader data
# 
#  could be easily expanded to read a text file with sources
#  i.e. using add_readers_from_list()
# 
# ======================================================================
imp:  test_config_OpenDrift # implementation name
model: OceanDrift3D
rootdir: 'C:\tests\'# where the simulation will be run
# extra_model_args: {logfile: 'test.log','weathering_model','noaa'}# these will be passed as **kwargs in __init__() function
# e.g. extra_model_args: {logfile: 'test.log','weathering_model','noaa'}
# ======================================================================
# release
nb_parts: 100
start_time: '20-06-2019 00:00'
end_time:   '20-06-2019 00:00'
# duration_hours: 24.0 #= int(self.durationhours.get())*3600/time_step
end_time_run: '22-06-2019 00:00' #not used if duration is specified
time_step_sec: 900 #= 900  # 15 minutes
time_step_sec_output: 1800 #= timedelta(minutes=30)
position: {lon: 11.0,lat: 70.0, radius: 20.,z: 0.0} # z can be 'seafloor' or 'seafloor+2', or scalar -50.0
# end_position: {elon: 174.1656,elat: -40.3346, eradius: 10.,ez: 0.0} #  optional, final lon,lat,z
extra_seed_args: {} # these will be passed as **kwargs in seed_elements() function
# e.g. extra_seed_args: {objectType: 26} # 26 = Life-raft, no ballast
# frame
model_frame:    {llcrnrlon: 9.5, llcrnrlat: 68.8 , urcrnrlon: 19.0 , urcrnrlat: 71.2}
basemap_resolution: 'h' # resolution can be c (crude, the default), l (low), i (intermediate), h (high), f (full)
# ======================================================================
# readers
# specified using {reader_type: reader_filename, ...} reader_type can be any found in 'from opendrift.readers'  
readers:
    ocean0: # specify one or several reader_type and filenames - order matters and will govern priority
        reader_type: [reader_netCDF_CF_generic] #reader_type can be any found in 'from opendrift.readers'  
        filename: ['http://thredds.met.no/thredds/dodsC/sea/norkyst800m/1h/aggregate_be']
    ocean1: # specify one or several reader_type and filenames - order matters and will govern priority
        reader_type: [reader_netCDF_CF_generic] #reader_type can be any found in 'from opendrift.readers'  
        filename: ['http://thredds.met.no/thredds/dodsC/sea/nordic4km/zdepths1h/aggregate_be'] #

fallback_values: {ocean_vertical_diffusivity: 0.0001} # used to define constant/fall back values
# ======================================================================
run_backwards: False
stop_on_error: True
outfile: output_uds.nc #self.outputdir + '/opendrift_'  # could be defined by default from implemtation name ?
extra_output_args: {} # additional outputs arguments as specified in run()
# ======================================================================
# configuration : base inherited from basemodel + model-specific configs 
# e.g.
# https://github.com/OpenDrift/opendrift/blob/1323f4a47cb16b2ebd818d6c3c302036331e36a7/opendrift/models/basemodel.py#L123
# https://github.com/OpenDrift/opendrift/blob/1323f4a47cb16b2ebd818d6c3c302036331e36a7/opendrift/models/opendrift3D.py#L55
# https://github.com/OpenDrift/opendrift/blob/1323f4a47cb16b2ebd818d6c3c302036331e36a7/opendrift/models/opendrift3D.py#L55
# 
# if nothing specfied, default config is used 
config:
    general:
        coastline_action: 'stranding' # option('none', 'stranding', 'previous', default='stranding')
    seed:
        ocean_only: True #boolean(default=True)
    drift:
        scheme: 'runge-kutta4'
        current_uncertainty: 0.00
        wind_uncertainty: 2.0
    processes:
        turbulentmixing: False
        verticaladvection: False
# post-processing
post_process:
    show_anim:  False
    save_anim:  False
    show_plot:  True
    save_plot:  False
    show_oil_budget: False
    save_oil_budget: False
    # more to come